### ISSUE TITLE
Value equality

### ISSUE THREAD

**Issue by swanandp** [stitchfix/immutable-struct#11]
`Struct` also provides a built in value based equality:

```Ruby
Person = Struct.new(:name, :age)
john = Person.new("john", 20)
not_jake = Person.new("john", 20)

john == not_jake # true
```

`ImmutableStruct` currently breaks this behaviour ( or more appropriately, doesn't offer this feature ).

**Comment by simeonwillbanks** [comment]
:+1: 

Reference implementations from Ruby 2.2.3:

 - [`OpenStruct#==`](https://github.com/ruby/ruby/blob/v2_2_3/lib/ostruct.rb#L260-L268)
 - [`Struct#==`](https://github.com/ruby/ruby/blob/v2_2_3/struct.c#L926-L952)

**Comment by billeisenhauer** [comment]
Closing.  Thanks @swanandp for reporting the issue!

**Comment by swanandp** [comment]
Cool, thanks for adding this!
