### ISSUE TITLE
Repo description link 404ing

### ISSUE THREAD

**Issue by mbigras** [stitchfix/immutable-struct#25]
The description is currently linking to https://opensource.stitchfix.com/immutable-struct

But it doesn't exist:

```sh
curl -I https://opensource.stitchfix.com/immutable-struct
HTTP/1.1 404 Not Found
Content-Length: 1564
Content-Type: text/html; charset=utf-8
Strict-Transport-Security: max-age=15552000
X-Request-Id: e30158fe-bd2b-453c-93a7-8d990cb464b9
X-Runtime: 0.001344
Connection: keep-alive
```

Is the intended link to the blog post http://multithreaded.stitchfix.com/blog/2013/12/20/presenters-delegation-vs-structs/ ?

**Comment by davetron5000** [comment]
D'oh, that was from when opensource was hosted on GH pages.  The correct link should be : https://stitchfix.github.io/immutable-struct/  Switching it now…
