### ISSUE TITLE
JRuby support status

### ISSUE THREAD

**Issue by nandosola** [stitchfix/immutable-struct#6]
I've just run the specs against:
- `jruby 9.0.0.0.rc1 (2.2.2) 2015-06-10 a0bf3b3 Java HotSpot(TM) 64-Bit Server VM 25.45-b02 on 1.8.0_45-b14 +jit [darwin-x86_64]`
- `jruby 1.7.20.1 (1.9.3p551) 2015-06-10 d7c8c27 on Java HotSpot(TM) 64-Bit Server VM 1.8.0_45-b14 +jit [darwin-x86_64]`

Without any errors. What would be the reason behind ade2471be26a16b4d319fd8a62446a884c6a2cff?

**Comment by davetron5000** [comment]
I think they failed on travis and since we aren't using JRuby it wasn't worth the time to figure out why.  I **would** prefer this support as many rubies as possible though.  You want to try adding it to `.travis.yml` and see if it's working?

**Comment by nandosola** [comment]
Sure thing! I have to leave now, but I'll keep you posted.

Have a good weekend!
